project_id = "tsltxvswzdnlmvljpryh"

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.chat-with-agent]
verify_jwt = true

[functions.chat-orchestrator]
verify_jwt = true

[functions.invite-employee]
verify_jwt = true

[functions.verify-turnstile]
verify_jwt = false
